import random
from typing import List, Tuple
 
import json
from models import InstanceData, Solution
from models.solver import Solver
import sys
 
class GeneticAlgorithmSolver:
        def __init__(self, instance: InstanceData, initial_solution: Solution):
            self.instance = instance
            self.initial_solution = initial_solution
            self.population_size = 50
            self.tournament_size = 10
            self.mutation_prob = 1
            self.hill_climbing_steps = 100 
            self.solver = Solver()
 

        # TODO: Uncomment if you want to use neps and GPU
         
         #  This constructor sets up all the necessary configuration for running a genetic algorithm, including support for GPU acceleration if available. 
         #  The parameters are flexible, allowing for easy experimentation.
       
        #  def __init__(self, instance: InstanceData, initial_solution: Solution,
        #          population_size=50, mutation_prob=1,
        #          hill_climbing_steps=100, tabu_length=10):
        #     self.instance = instance
        #     self.initial_solution = initial_solution
        #     self.population_size = population_size
        #     self.tournament_size = max(2, population_size // 5)  # Dynamic tournament size
        #     self.mutation_prob = mutation_prob
        #     self.hill_climbing_steps = hill_climbing_steps
        #     self.tabu_length = tabu_length
        #     self.solver = Solver()
        #     self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        def load(self, file_path):
            """
            Loads and returns data from a JSON file.

            Args:
                file_path (str): The path to the JSON file to be loaded.

            Returns:
                dict: The data loaded from the JSON file.

            Raises:
                FileNotFoundError: If the specified file does not exist.
                json.JSONDecodeError: If the file is not a valid JSON.
            """
            with open(file_path, 'r') as f:
                data = json.load(f)
            return data
 
        def generate_initial_solution(self, instance):
            """
            Generate an initial solution for the given instance using the GRASP heuristic.

            Args:
                instance: The problem instance for which to generate an initial solution.

            Returns:
                An initial solution generated by the GRASP method.

            Notes:
                This method delegates the solution generation to the solver's
                `generate_initial_solution_grasp` method with a maximum time limit of 30 seconds.
            """
            """Generate initial solution using GRASP"""
            return self.solver.generate_initial_solution_grasp(instance, max_time=30)
    
        def solve(self) -> Solution:
            """
            Runs the genetic algorithm to find an optimal or near-optimal solution.
            This method initializes a population, then iteratively evolves it using selection,
            crossover, and mutation (with optional feature-based tabu search as mutation).
            It tracks the best solution found and implements early stopping if no improvement
            is observed for a specified number of generations (patience).
            Returns:
                Solution: The best solution found by the genetic algorithm.
            """
            population = self.initialize_population(self.initial_solution)
            best_solution = max(population, key=lambda x: x.fitness_score)
            best_score = best_solution.fitness_score

            no_improvement_counter = 0
            patience = 10  

            for generation in range(self.population_size):
                print(f"Gen {generation}: Best fitness = {best_score}")

                new_population = [best_solution]  

                while len(new_population) < self.population_size:
                    parent1 = self.tournament_select(population)
                    parent2 = self.tournament_select(population)

                    offspring1, offspring2 = self.crossover(parent1, parent2)

                    for offspring in (offspring1, offspring2):
                        if random.random() < self.mutation_prob:
                            offspring = self.solver.feature_based_tabu_search(
                                offspring, self.instance, max_iterations=self.hill_climbing_steps
                            )
                        new_population.append(offspring)

                population = new_population[:self.population_size]
                population.sort(key=lambda x: x.fitness_score)
                current_best = population[0]

                if current_best is not best_solution:
                    best_solution = current_best
                    best_score = current_best.fitness_score
                    no_improvement_counter = 0
                else:
                    no_improvement_counter += 1

                if no_improvement_counter >= patience:
                    print(f"Early stopping: No improvement for {patience} generations.")
                    break

            return best_solution
    
        def initialize_population(self, initial_solution: Solution) -> List[Solution]:
            """
            Initializes the population for the genetic algorithm by generating variations of the given initial solution.
            Args:
                initial_solution (Solution): The base solution from which to generate population variants.
            Returns:
                List[Solution]: A list containing the initial solution and its generated variants, forming the initial population.
            """
            population = [self.initial_solution]
    
            while len(population) < self.population_size:
                variant_fitness, variant = self.solver.hill_climbing_combined_w_initial_solution(initial_solution, self.instance, iterations=5)
                population.append(variant)
    
            return population
        
        def tournament_select(self, population: List[Solution]) -> Solution:
            """
            Selects the best solution from a randomly chosen subset of the population.

            This method performs tournament selection by randomly sampling `tournament_size` individuals
            from the given population and returning the one with the highest fitness score.

            Args:
                population (List[Solution]): The list of candidate solutions to select from.

            Returns:
                Solution: The solution with the highest fitness score among the sampled candidates.
            """
            tournament = random.sample(population, self.tournament_size)
            return max(tournament, key=lambda x: x.fitness_score)

        def crossover(self, parent1: Solution, parent2: Solution) -> Tuple[Solution, Solution]:
            """
            Performs a two-point crossover operation between two parent solutions to generate two offspring solutions.
            This method applies a two-point crossover on the `signed_libraries` attribute of each parent, ensuring that the offspring inherit a mix of library orderings from both parents while maintaining valid library indices and avoiding duplicates. After crossover, it reconstructs the offspring solutions by selecting libraries and books according to problem constraints, recalculates their fitness scores, and returns the resulting offspring.
            Args:
                parent1 (Solution): The first parent solution.
                parent2 (Solution): The second parent solution.
            Returns:
                Tuple[Solution, Solution]: A tuple containing two offspring solutions generated from the parents. If crossover is not possible or fails, returns the original parents.
            Notes:
                - If either parent has fewer than two signed libraries, crossover is skipped and the parents are returned unchanged.
                - If an exception occurs during crossover or offspring construction, the parents are returned after recalculating their fitness scores.
            """
            def two_point_crossover(p1_signed, p2_signed):
                size = len(p1_signed)
                
                if size < 2:
                    return p1_signed.copy()

                point1 = random.randint(0, size - 2)
                point2 = random.randint(point1 + 1, size - 1)

                offspring = [None] * size
                offspring[point1:point2] = p1_signed[point1:point2]
                used = set(offspring[point1:point2])

                p2_idx = 0
                for i in range(size):
                    if offspring[i] is None:
                        while p2_idx < size and p2_signed[p2_idx] in used:
                            p2_idx += 1
                        if p2_idx < size:
                            offspring[i] = p2_signed[p2_idx]
                            used.add(p2_signed[p2_idx])
                            p2_idx += 1
                        else:
                            offspring[i] = -1  

                return offspring

            try:
                if len(parent1.signed_libraries) < 2 or len(parent2.signed_libraries) < 2:
                    print("Crossover skipped due to small parent size.")
                    return parent1, parent2

                offspring1_signed = two_point_crossover(parent1.signed_libraries, parent2.signed_libraries)
                offspring2_signed = two_point_crossover(parent2.signed_libraries, parent1.signed_libraries)

                def build_solution(signed_libs):
                    scanned_books = set()
                    scanned_per_lib = {}
                    used_libs = []

                    current_day = 0
                    for lib in signed_libs:
                        if lib < 0 or lib >= self.instance.num_libs:
                            continue

                        lib_data = self.instance.libs[lib]

                        if current_day + lib_data.signup_days > self.instance.num_days:
                            continue

                        current_day += lib_data.signup_days
                        remaining_days = self.instance.num_days - current_day
                        max_books = remaining_days * lib_data.books_per_day

                        available_books = [
                            b.id for b in lib_data.books
                            if b.id not in scanned_books and 0 <= b.id < self.instance.num_books
                        ]

                        available_books.sort(key=lambda x: self.instance.scores[x], reverse=True)
                        selected = available_books[:max_books]

                        if selected:
                            scanned_books.update(selected)
                            scanned_per_lib[lib] = selected
                            used_libs.append(lib)

                    return Solution(
                        signed_libs=used_libs,
                        unsigned_libs=list(set(range(self.instance.num_libs)) - set(used_libs)),
                        scanned_books_per_library=scanned_per_lib,
                        scanned_books=scanned_books
                    )
            
                offspring1 = build_solution(offspring1_signed)
                offspring2 = build_solution(offspring2_signed)
                
                offspring1.calculate_fitness_score(self.instance.scores)
                offspring2.calculate_fitness_score(self.instance.scores)
                
                return (offspring1, offspring2)

            except Exception as e:
                print(f"Crossover failed: {e}, returning parents")
                parent1.calculate_fitness_score(self.instance.scores)
                parent2.calculate_fitness_score(self.instance.scores)
                return parent1, parent2
